modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="shyrium"
version="0.0.3.5"
displayName="Shyrium"
credits="By Shyro And Nalaxyzz"
displayURL="https://discord.gg/NwxKsXKpgQ"
authors="Nalaxyzz "
description='''
By Shyro And Nalaxyzz
'''

[[dependencies.shyrium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"



[[dependencies.shyrium]]
    modId="just_enough_items"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

